### ISSUE TITLE
Error when compiling: variable 'A_STORE' with dynamic initialization put into program memory area

### ISSUE THREAD

**Issue by JonTabor** [ChocolateFrogsNuts/BitXUltra#1]
First off, thanks for creating this, I'm excited about the possibilities for some of the features.

When compiling with HAVE_CHANNELS set to 1, I get the following error, and I'm not having any luck figuring out why.

```
Arduino: 1.8.13 (Linux), Board: "Arduino Nano, ATmega328P"

sketch/menu.cpp: In function 'h_store':
menu.cpp:191:14: error: variable 'A_STORE' with dynamic initialization put into program memory area
              defineAdjustment(A_STORE, S_STORETO, 0, state.channelCount-1, 1, NULL, &c_store, &s_store);
              ^
lto-wrapper: fatal error: /home/taborj/arduino-1.8.13/hardware/tools/avr/bin/avr-gcc returned 1 exit status
compilation terminated.
/home/taborj/arduino-1.8.13/hardware/tools/avr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
exit status 1
variable 'A_STORE' with dynamic initialization put into program memory area

```

Any thoughts?

**Comment by JonTabor** [comment]
Found the issue, for anyone else that may come after me.  Here's a workaround.

In menu.cpp, change this line:

`defineAdjustment(A_STORE, S_STORETO, 0, state.channelCount-1, 1, NULL, &c_store, &s_store);`

To this:

`defineAdjustment(A_STORE, S_STORETO, 0, 9, 1, NULL, &c_store, &s_store);`

The current compiler doesn't like sending a dynamic variable in (`state.channelCount-1`), so we just hard-code it to the number of channels we want (look in `config.h` for `CHANNEL_COUNT` and then subtract one, because the channels start at 0).

**Comment by ChocolateFrogsNuts** [comment]
Ahh, thanks for that.

coding it as CHANNEL_COUNT-1 should also work then...

JonTabor wrote on 13/02/2021 06:02:
